services:
  rabbitmq:
    image: rabbitmq:4.3.0-management
    healthcheck:
      # 이 명령이 성공 -> docker가 이 컨테이너를 healthy 상태로 봄
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER} 
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  mongodb:
    image: "mongodb/mongodb-community-server:8.2.9-ubuntu2204-slim"
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  rabbitmq-consumer:
    build: ./rabbitmq_consumer
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      PUSHOVER_TOKEN: ajsqj5bv3zee17c29z5gzhoyqmz2w8
      PUSHOVER_USER: ukwcz2buto4x3zrmfoffnregy4c27n
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  mongodb_data: